-- 112: Seed 18 pre-built automation templates into the marketplace
-- These are system-published templates users can browse and import into their projects.

INSERT IGNORE INTO automation_marketplace (id, name, description, category, tags, trigger_event_type, scope, definition, max_runs_per_day, cooldown_seconds, published_by_org_id, published_by_org_name, published_by_user_id, download_count) VALUES

-- Deadline Management
('atpl-0001-crit-path-esc', 'Escalate Critical Path Tasks', 'Escalate to the project owner when a task on the critical path falls behind.', 'Deadline Management', '["critical-path","escalation","schedule"]', 'task.status_changed', 'project', '{"conditions":{"logic":"and","conditions":[{"field":"isCritical","operator":"equals","value":true},{"field":"status","operator":"in","value":["at_risk","delayed","blocked"]}]},"actions":[{"id":"a1","type":"escalate","runOrder":0,"params":{"recipients":"project_owner","messageTemplate":"Critical path task \\"{{entity.name}}\\" is now {{entity.status}}. This may impact the project end date.","title":"Critical Path Task At Risk"}},{"id":"a2","type":"log_audit","runOrder":1,"params":{"messageTemplate":"Critical path task \\"{{entity.name}}\\" status changed to {{entity.status}}","action":"critical_path_alert"}}]}', 50, 3600, 'system', 'Kovarti', 'system', 0),

('atpl-0002-notify-assign', 'Notify Assignee on Task Assignment', 'Send a notification to the assigned team member when a task is assigned to them.', 'Deadline Management', '["assignment","notification","onboarding"]', 'task.assigned', 'project', '{"actions":[{"id":"a1","type":"notify","runOrder":0,"params":{"recipients":"assignee","messageTemplate":"You have been assigned task \\"{{entity.name}}\\" in project {{project.name}}. Priority: {{entity.priority}}.","title":"New Task Assigned to You","severity":"medium"}}]}', 50, 0, 'system', 'Kovarti', 'system', 0),

('atpl-0003-auto-close-100', 'Auto-Close Tasks at 100% Progress', 'Automatically set task status to completed when progress reaches 100%.', 'Deadline Management', '["progress","auto-complete","status"]', 'task.updated', 'project', '{"conditions":{"logic":"and","conditions":[{"field":"progressPercentage","operator":"greater_equal","value":100},{"field":"status","operator":"not_equals","value":"completed"}]},"actions":[{"id":"a1","type":"change_status","runOrder":0,"params":{"newStatus":"completed"}}]}', 50, 0, 'system', 'Kovarti', 'system', 0),

-- Status Workflow
('atpl-0004-status-regress', 'Flag Backward Status Changes', 'Log an audit entry and notify the project owner when a task moves backward in status.', 'Status Workflow', '["workflow","regression","audit"]', 'task.status_changed', 'project', '{"conditions":{"logic":"and","conditions":[{"field":"previous.status","operator":"in","value":["in_progress","completed"]},{"field":"status","operator":"equals","value":"not_started"}]},"actions":[{"id":"a1","type":"notify","runOrder":0,"params":{"recipients":"project_owner","messageTemplate":"Task \\"{{entity.name}}\\" was moved backward from {{previous.status}} to {{entity.status}} by {{user.email}}.","title":"Status Regression Detected","severity":"high"}},{"id":"a2","type":"log_audit","runOrder":1,"params":{"messageTemplate":"Task \\"{{entity.name}}\\" status regressed from {{previous.status}} to {{entity.status}}","action":"status_regression"}}]}', 50, 0, 'system', 'Kovarti', 'system', 0),

('atpl-0005-project-on-hold', 'Notify Team When Project On Hold', 'Notify the project owner when a project is placed on hold.', 'Status Workflow', '["project","on-hold","notification"]', 'project.status_changed', 'project', '{"conditions":{"logic":"and","conditions":[{"field":"status","operator":"in","value":["on_hold","paused"]}]},"actions":[{"id":"a1","type":"notify","runOrder":0,"params":{"recipients":"project_owner","messageTemplate":"Project \\"{{project.name}}\\" has been placed on hold. Previous status: {{previous.status}}.","title":"Project On Hold","severity":"high"}}]}', 50, 0, 'system', 'Kovarti', 'system', 0),

-- Risk & Quality
('atpl-0006-blocked-risk', 'Auto-Create Risk for Blocked Tasks', 'Automatically register a risk item when any task is marked as blocked.', 'Risk & Quality', '["blocked","risk","auto-create"]', 'task.status_changed', 'project', '{"conditions":{"logic":"and","conditions":[{"field":"status","operator":"equals","value":"blocked"}]},"actions":[{"id":"a1","type":"add_risk","runOrder":0,"params":{"title":"Blocked task: {{entity.name}}","type":"issue","severity":"high","description":"Task \\"{{entity.name}}\\" has been blocked. Investigate and resolve the blocker.","category":"schedule"}},{"id":"a2","type":"notify","runOrder":1,"params":{"recipients":"project_owner","messageTemplate":"Task \\"{{entity.name}}\\" is blocked. A risk item has been auto-created.","title":"Blocked Task Detected","severity":"high"}}]}', 50, 0, 'system', 'Kovarti', 'system', 0),

('atpl-0007-risk-sev-esc', 'Escalate Risk Severity Increase', 'Escalate when a risk severity is upgraded to high or critical.', 'Risk & Quality', '["risk","severity","escalation"]', 'risk.updated', 'project', '{"conditions":{"logic":"and","conditions":[{"field":"severity","operator":"in","value":["high","critical"]},{"field":"previous.severity","operator":"in","value":["low","medium"]}]},"actions":[{"id":"a1","type":"escalate","runOrder":0,"params":{"recipients":"project_owner","messageTemplate":"Risk \\"{{entity.title}}\\" severity upgraded from {{previous.severity}} to {{entity.severity}}. Review recommended.","title":"Risk Severity Escalation"}}]}', 50, 0, 'system', 'Kovarti', 'system', 0),

-- Team Communication
('atpl-0008-welcome-comment', 'Welcome Comment on New Task', 'Automatically add a comment to new high-priority tasks with guidance for the assignee.', 'Team Communication', '["comment","onboarding","priority"]', 'task.created', 'project', '{"conditions":{"logic":"and","conditions":[{"field":"priority","operator":"in","value":["high","critical"]}]},"actions":[{"id":"a1","type":"add_comment","runOrder":0,"params":{"messageTemplate":"This is a {{entity.priority}}-priority task. Please review the requirements and provide an initial estimate within 24 hours."}}]}', 50, 0, 'system', 'Kovarti', 'system', 0),

('atpl-0009-sprint-kickoff', 'Email Sprint Kickoff Notice', 'Send an email to the project owner when a sprint starts with goal and date details.', 'Team Communication', '["sprint","email","kickoff"]', 'sprint.started', 'project', '{"actions":[{"id":"a1","type":"send_email","runOrder":0,"params":{"to":"project_owner","subject":"Sprint Started: {{entity.name}}","body":"Sprint \\"{{entity.name}}\\" has kicked off in project {{project.name}}.\\n\\nGoal: {{entity.goal}}\\nStart: {{entity.startDate}}\\nEnd: {{entity.endDate}}\\n\\nPlease review the sprint backlog and ensure all tasks are assigned."}}]}', 50, 0, 'system', 'Kovarti', 'system', 0),

('atpl-0010-cr-returned', 'Notify CR Author on Return', 'Notify the change request creator when their request is returned for revision.', 'Team Communication', '["change-request","revision","feedback"]', 'change_request.returned', 'project', '{"actions":[{"id":"a1","type":"notify","runOrder":0,"params":{"recipients":"creator","messageTemplate":"Your change request \\"{{entity.title}}\\" has been returned for revision. Please review the feedback and resubmit.","title":"Change Request Needs Revision","severity":"medium"}}]}', 50, 0, 'system', 'Kovarti', 'system', 0),

-- Resource Management
('atpl-0011-round-robin', 'Round-Robin Task Assignment', 'Automatically distribute new unassigned tasks across team members using round-robin.', 'Resource Management', '["assignment","round-robin","workload"]', 'task.created', 'project', '{"conditions":{"logic":"and","conditions":[{"field":"assignedTo","operator":"is_empty"}]},"actions":[{"id":"a1","type":"auto_assign","runOrder":0,"params":{"strategy":"round_robin"}},{"id":"a2","type":"notify","runOrder":1,"params":{"recipients":"assignee","messageTemplate":"You have been auto-assigned task \\"{{entity.name}}\\" in {{project.name}}.","title":"New Task Auto-Assigned","severity":"low"}}]}', 50, 0, 'system', 'Kovarti', 'system', 0),

('atpl-0012-excessive-hours', 'Flag Excessive Daily Hours', 'Notify the project owner when someone logs more than 12 hours in a single time entry.', 'Resource Management', '["time-tracking","overwork","alert"]', 'time_entry.created', 'project', '{"conditions":{"logic":"and","conditions":[{"field":"hours","operator":"greater_than","value":12}]},"actions":[{"id":"a1","type":"notify","runOrder":0,"params":{"recipients":"project_owner","messageTemplate":"{{user.email}} logged {{entity.hours}} hours in a single entry on project {{project.name}}. This may indicate overwork or a data entry error.","title":"Excessive Hours Logged","severity":"high"}}]}', 50, 86400, 'system', 'Kovarti', 'system', 0),

-- AI-Powered
('atpl-0013-ai-retro', 'AI Sprint Retrospective', 'Use AI to generate a retrospective summary when a sprint completes.', 'AI-Powered', '["ai","sprint","retrospective","summary"]', 'sprint.completed', 'project', '{"actions":[{"id":"a1","type":"ai_generate","runOrder":0,"params":{"prompt":"Generate a sprint retrospective summary for sprint \\"{{entity.name}}\\" in project {{project.name}}. Sprint goal was: {{entity.goal}}. Include sections for: What went well, What could improve, and Action items for the next sprint. Keep it concise (3-4 bullets per section).","outputKey":"retrospective","maxTokens":800}},{"id":"a2","type":"notify","runOrder":1,"params":{"recipients":"project_owner","messageTemplate":"Sprint Retrospective for \\"{{entity.name}}\\":\\n\\n{{ai.retrospective}}","title":"AI Sprint Retrospective Ready","severity":"low"}}]}', 50, 0, 'system', 'Kovarti', 'system', 0),

('atpl-0014-ai-risk-mitig', 'AI Risk Mitigation Advisor', 'When a high or critical risk is created, use AI to suggest mitigation strategies.', 'AI-Powered', '["ai","risk","mitigation","advisory"]', 'risk.created', 'project', '{"conditions":{"logic":"and","conditions":[{"field":"severity","operator":"in","value":["high","critical"]}]},"actions":[{"id":"a1","type":"ai_generate","runOrder":0,"params":{"prompt":"A {{entity.severity}}-severity {{entity.type}} has been identified in project {{project.name}}: \\"{{entity.title}}\\". Description: {{entity.description}}. Suggest 3 specific, actionable mitigation strategies. For each, provide: the strategy name, what to do, and expected risk reduction.","outputKey":"mitigations","maxTokens":600}},{"id":"a2","type":"notify","runOrder":1,"params":{"recipients":"project_owner","messageTemplate":"AI mitigation suggestions for risk \\"{{entity.title}}\\":\\n\\n{{ai.mitigations}}","title":"AI Risk Mitigation Suggestions","severity":"medium"}}]}', 50, 0, 'system', 'Kovarti', 'system', 0),

('atpl-0015-ai-task-enrich', 'AI Task Description Enrichment', 'When a task is created with an empty description, use AI to generate acceptance criteria.', 'AI-Powered', '["ai","task","description","enrichment"]', 'task.created', 'project', '{"conditions":{"logic":"and","conditions":[{"field":"description","operator":"is_empty"}]},"actions":[{"id":"a1","type":"ai_generate","runOrder":0,"params":{"prompt":"A task named \\"{{entity.name}}\\" has been created in project {{project.name}} with priority {{entity.priority}} but no description. Generate a brief task description with: 1) A one-sentence summary of what this task likely involves based on its name, 2) 3 acceptance criteria, 3) A suggested approach. Keep it concise.","outputKey":"enriched","maxTokens":400}},{"id":"a2","type":"add_comment","runOrder":1,"params":{"messageTemplate":"AI-suggested task details:\\n\\n{{ai.enriched}}\\n\\n(Auto-generated -- please review and edit as needed.)"}}]}', 50, 0, 'system', 'Kovarti', 'system', 0),

('atpl-0016-extract-lessons', 'Extract Lessons on Project Completion', 'Automatically extract lessons learned when a project is marked as completed.', 'AI-Powered', '["ai","lessons-learned","completion","knowledge"]', 'project.status_changed', 'project', '{"conditions":{"logic":"and","conditions":[{"field":"status","operator":"equals","value":"completed"}]},"actions":[{"id":"a1","type":"extract_lesson","runOrder":0,"params":{}},{"id":"a2","type":"notify","runOrder":1,"params":{"recipients":"project_owner","messageTemplate":"Project \\"{{project.name}}\\" has been completed. Lessons learned have been automatically extracted and stored for future projects.","title":"Lessons Learned Extracted","severity":"low"}}]}', 50, 0, 'system', 'Kovarti', 'system', 0),

-- Compliance & Audit
('atpl-0017-task-delete-audit', 'Audit Trail for Task Deletions', 'Log an audit entry whenever a task is deleted for compliance and traceability.', 'Compliance & Audit', '["audit","deletion","compliance"]', 'task.deleted', 'project', '{"actions":[{"id":"a1","type":"log_audit","runOrder":0,"params":{"messageTemplate":"Task \\"{{entity.name}}\\" ({{entity.status}}, assigned to {{entity.assignedTo}}) was deleted by {{user.email}}","action":"task_deleted"}},{"id":"a2","type":"notify","runOrder":1,"params":{"recipients":"project_owner","messageTemplate":"Task \\"{{entity.name}}\\" was deleted from project {{project.name}} by {{user.email}}.","title":"Task Deleted","severity":"medium"}}]}', 50, 0, 'system', 'Kovarti', 'system', 0),

('atpl-0018-timesheet-submit', 'Timesheet Submission Confirmation', 'Notify the submitter and project owner when a timesheet is submitted for approval.', 'Compliance & Audit', '["timesheet","approval","notification"]', 'timesheet.submitted', 'project', '{"actions":[{"id":"a1","type":"notify","runOrder":0,"params":{"recipients":"trigger_user","messageTemplate":"Your timesheet has been submitted for approval in project {{project.name}}.","title":"Timesheet Submitted","severity":"low"}},{"id":"a2","type":"notify","runOrder":1,"params":{"recipients":"project_owner","messageTemplate":"A timesheet has been submitted for approval by {{user.email}} in project {{project.name}}. Please review and approve.","title":"Timesheet Pending Approval","severity":"medium"}}]}', 50, 0, 'system', 'Kovarti', 'system', 0);
