-- Migration 122 (2026-09-30): every plan gets its feature list.
-- 070 never seeded 'enterprise', and production's tier_features holds only the two
-- Consultant plans (trial / sme rows are missing too). A missing row means "feature off",
-- so SME and Enterprise customers would have been refused Resources, reports, EVM, exports,
-- the API and more (found when an Enterprise QA account couldn't add a rate card line).
-- INSERT IGNORE: existing rows (and any deliberate on/off choice) are left alone.
INSERT IGNORE INTO tier_features (id, tier, feature_key, enabled) VALUES
  (UUID(), 'trial', 'api_keys', 0),
  (UUID(), 'trial', 'auto_reschedule', 0),
  (UUID(), 'trial', 'cross_project_intelligence', 0),
  (UUID(), 'trial', 'evm', 0),
  (UUID(), 'trial', 'exports', 0),
  (UUID(), 'trial', 'meeting_intelligence', 0),
  (UUID(), 'trial', 'monte_carlo', 0),
  (UUID(), 'trial', 'nl_query', 0),
  (UUID(), 'trial', 'portal', 0),
  (UUID(), 'trial', 'reports', 0),
  (UUID(), 'trial', 'resources', 0),
  (UUID(), 'trial', 'workflows', 0),
  (UUID(), 'sme', 'api_keys', 1),
  (UUID(), 'sme', 'auto_reschedule', 1),
  (UUID(), 'sme', 'cross_project_intelligence', 1),
  (UUID(), 'sme', 'evm', 1),
  (UUID(), 'sme', 'exports', 1),
  (UUID(), 'sme', 'meeting_intelligence', 1),
  (UUID(), 'sme', 'monte_carlo', 1),
  (UUID(), 'sme', 'nl_query', 1),
  (UUID(), 'sme', 'portal', 1),
  (UUID(), 'sme', 'reports', 1),
  (UUID(), 'sme', 'resources', 1),
  (UUID(), 'sme', 'workflows', 1),
  (UUID(), 'enterprise', 'api_keys', 1),
  (UUID(), 'enterprise', 'auto_reschedule', 1),
  (UUID(), 'enterprise', 'cross_project_intelligence', 1),
  (UUID(), 'enterprise', 'evm', 1),
  (UUID(), 'enterprise', 'exports', 1),
  (UUID(), 'enterprise', 'meeting_intelligence', 1),
  (UUID(), 'enterprise', 'monte_carlo', 1),
  (UUID(), 'enterprise', 'nl_query', 1),
  (UUID(), 'enterprise', 'portal', 1),
  (UUID(), 'enterprise', 'reports', 1),
  (UUID(), 'enterprise', 'resources', 1),
  (UUID(), 'enterprise', 'workflows', 1);
